""" <br>
@Author: Girish <br>
@Date: 2024-08-08 <br>
@Last Modified by: Girish <br>
@Last Modified time: 2024-08-08 <br>
@Title: Pandas Library Problems <br>
"""

In [26]:
import numpy as np
import pandas as pd

1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.

In [27]:

def main():
    
        
    '''
    Description :
        Creates 1-d array in pandas and prints it
    
    parameter :
        None
    
    return : 
        None
    '''
    
    
    arr = [1,2,3,4,5,6]
    pandas_array = pd.array(data = arr, dtype= int)
    print(f"pandas array : {pandas_array}")



if __name__ == "__main__":
    main()

pandas array : <NumpyExtensionArray>
[1, 2, 3, 4, 5, 6]
Length: 6, dtype: int32

2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [28]:

def pd_series_to_list(pd_series):
    
    """
    Description:
        This function converts a Pandas Series to a list.

    Parameters:
        pd_series (pd.Series): The Series that needs to be converted to a list.
    
    Returns: 
        list: The converted list.
    """    
    
    return pd_series.tolist()



def main():
    pd_series = pd.Series([1, 2, 3, 4, 5, 6])
    print(f'Pandas Series:\n{pd_series}')
    
    my_list = pd_series_to_list(pd_series)
    print(f'Converted List: {my_list}')


if __name__ == "__main__":
    main()

Pandas Series:
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Converted List: [1, 2, 3, 4, 5, 6]

3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [29]:


def perform_operations(series1, series2):
    
    
    '''
    Description :
        This function performs addition, subtraction, multiplication, and division 
        on two provided Pandas Series and prints the results.
    
    Parameters :
        series1 : pd.Series : The first Pandas Series
        series2 : pd.Series : The second Pandas Series
    
    Returns :
        None
    '''    
    
    
    addition = series1 + series2
    print(f"Addition:\n{addition}\n")

    subtraction = series1 - series2
    print(f"Subtraction:\n{subtraction}\n")

    multiplication = series1 * series2
    print(f"Multiplication:\n{multiplication}\n")

    
    division = series1 / series2
    print(f"Division:\n{division}\n")



def main():

    series1 = pd.Series([2, 4, 6, 8, 10])
    series2 = pd.Series([1, 3, 5, 7, 9])

    print(f"Series 1:\n{series1}\n")
    print(f"Series 2:\n{series2}\n")
    
    perform_operations(series1, series2)

if __name__ == "__main__":
    main()

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0    1
1    3
2    5
3    7
4    9
dtype: int64

Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

4. Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array

In [30]:

def square_elements(arr):
    
    
    '''
    Description :
        This function squares each element in the provided Pandas array.
    
    Parameters :
        arr : pd.Array : The Pandas array whose elements need to be squared
    
    Returns :
        pd.Array : The modified Pandas array with squared elements
    '''   
    
     
    for index in range(len(arr)):
        arr[index] = arr[index] ** arr[index]
    return arr



def main():
    

    arr_1 = pd.array([2, 4, 6, 8, 10])
    print(f"Original Array:\n{arr_1}\n")
    
    squared_arr = square_elements(arr_1)
    print(f"Squared Array:\n{squared_arr}\n")

if __name__ == "__main__":
    main()

Original Array:
<IntegerArray>
[2, 4, 6, 8, 10]
Length: 5, dtype: Int64

Squared Array:
<IntegerArray>
[4, 256, 46656, 16777216, 10000000000]
Length: 5, dtype: Int64

5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels.

In [31]:

def create_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame from the given dictionary and labels.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
        DataFrame : The created Pandas DataFrame
    '''    
    
    
    return pd.DataFrame(data=data, index=labels)



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = create_dataframe(exam_data, labels)
    print("DataFrame:")
    print(df)

if __name__ == "__main__":
    main()

DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data.

In [32]:

def create_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame from the given dictionary and labels.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
        DataFrame : The created Pandas DataFrame
        Basic_info : Descriptin of the Data frame
        
    '''    
    
    
    return [pd.DataFrame(data=data, index=labels),pd.DataFrame(data=data, index=labels).describe()]



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = create_dataframe(exam_data, labels)
    print("DataFrames and its  Description:")
    print(df)

if __name__ == "__main__":
    main()

DataFrames and its  Description:
[        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes,            score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000]

7. Write a Python program to get the first 3 rows of a given DataFrame.

In [33]:

def create_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame from the given dictionary and labels.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
       3 row of dataframe
        
    '''    
    
    df = pd.DataFrame(data=data, index=labels)
    return df.iloc[0:3]



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = create_dataframe(exam_data, labels)
    print("DataFrames and its  Description:")
    print(df)

if __name__ == "__main__":
    main()

DataFrames and its  Description:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame.

In [34]:

def columns_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame from the given dictionary and labels.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
       Columns : name and score
        
    '''    
    
    df = pd.DataFrame(data=data, index=labels)
    return df[['name','score']]



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = columns_dataframe(exam_data, labels)
    print("Colums name and score :")
    print(df)

if __name__ == "__main__":
    main()

Colums name and score :
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

9. Write a Python program to select the specified columns and rows from a given data
frame.
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [35]:

def columns_rows_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame and select name and score column for rows 1,3,5,6.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
       Columns : name and score for rows 1,3,5,6
        
    '''    
    
    df = pd.DataFrame(data=data, index=labels)
    return df[['name','score']].iloc[[1,3,5,6]]



def main():


    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = columns_rows_dataframe(exam_data, labels)
    print("Colums name and score :")
    print(df)


if __name__ == "__main__":
    main()

Colums name and score :
      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

10.Write a Python program to select the rows where the number of attempts in the
examination is greater than 2.

In [36]:

def columns_rows_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame and select rows where attempts are > 2 .
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
       Dataframe : where attempts are greater than 2
        
    '''    
    
    df = pd.DataFrame(data=data, index=labels)
    return df[df['attempts'] > 2].iloc[:]



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = columns_rows_dataframe(exam_data, labels)
    print("data frame where attempts are greater than 2 :")
    print(df)

if __name__ == "__main__":
    main()

data frame where attempts are greater than 2 :
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

11. Write a Python program to count the number of rows and columns of a DataFrame.

In [37]:

import pandas as pd
import numpy as np

def len_rows_columns_dataframe(data, labels):
    
    
    '''
    Description:
        This function creates a DataFrame and select name and score column for rows 1,3,5,6.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
       number of colums and number of rows
        
    '''    
    
    df = pd.DataFrame(data=data, index=labels)
    return [len(df),len(df.columns)]



def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

   
    df = len_rows_columns_dataframe(exam_data, labels)
    print("Number of rows and columns respectively are  :")
    print(df)

if __name__ == "__main__":
    main()

Number of rows and columns respectively are  :
[10, 4]

12. Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [38]:

def create_and_display_dataframe(data, labels):
    
    
    """
    Description:
        This function creates a DataFrame from the given dictionary and labels,
        prints the DataFrame, and prints rows where the 'score' column contains NaN values.
    
    Parameters:
        data : dict : The dictionary containing the data
        labels : list : The list of labels to be used as index for the DataFrame
    
    Returns:
        None
    """
    
    
    df = pd.DataFrame(data=data, index=labels)
    nan_rows = df[pd.isna(df['score'])]
    print(f"\nRows with NaN values in column 'score':")
    print(nan_rows)


def main():

    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    
    create_and_display_dataframe(exam_data, labels)


if __name__ == "__main__":
    main()

Rows with NaN values in column 'score':
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15.

In [39]:

def create_and_filter_dataframe():
    
    
    """
    Description:
        Creates a pandas DataFrame from predefined exam data, filters the DataFrame
        based on specific conditions (attempts less than 2 and score greater than 15),
        and prints the filtered DataFrame.

    Parameters:
        None

    Returns:
        None
    """
 
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    df = pd.DataFrame(data=exam_data, index=labels)
   
    filtered_df = df[(df['attempts'] < 2) & (df['score'] > 15)]
    
   
    print("Filtered DataFrame:")
    print(filtered_df)

if __name__ == "__main__":
    create_and_filter_dataframe()

Filtered DataFrame:
    name  score  attempts qualify
j  Jonas   19.0         1     yes

14.Write a Python program to change the score in row 'd' to 11.5.

In [40]:


def create_and_update_dataframe():
    
    
    """
        
    Description:
        Creates a pandas DataFrame from predefined exam data, prints the DataFrame,
        updates a specific cell value, and then prints the updated DataFrame.

    Parameters:
        None

    Returns:
        None
        
        
    """
    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    df = pd.DataFrame(data=exam_data, index=labels)
    
    print("Original DataFrame:")
    print(df)
    print()
    
    df.loc['d', 'score'] = 11.5
    
    print("Updated DataFrame:")
    print(df)

if __name__ == "__main__":
    create_and_update_dataframe()

Original DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Updated DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

16. Write a Python program to calculate the mean score for each different student in
DataFrame.

In [41]:

def create_and_process_dataframe():
    
    
    """
    
    Description:
        Creates a pandas DataFrame from predefined exam data, calculates the mean score for each student,
        and prints the DataFrame with the mean scores included. Also computes and prints the mean of the 'score' column.

    Parameters:
        None

    Returns:
        None
        
    """
    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    df = pd.DataFrame(data=exam_data, index=labels)

    print("Initial DataFrame:")
    print(df)
    print()

    df['mean_score'] = df[['score']].apply(lambda x: x.mean(), axis=1)

    print(f"Mean of 'score' column: {df['score'].mean()}")
    
    print("DataFrame with Mean Scores:")
    print(df)
    
    

def main():

    create_and_process_dataframe()

if __name__ == "__main__":
    main()

Initial DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Mean of 'score' column: 13.5625
DataFrame with Mean Scores:
        name  score  attempts qualify  mean_score
a  Anastasia   12.5         1     yes        12.5
b       Dima    9.0         3      no         9.0
c  Katherine   16.5         2     yes        16.5
d      James    NaN         3      no         NaN
e      Emily    9.0         2      no         9.0
f    Michael   20.0         3     yes        20.0
g    Matthew   14.5         1     yes        14.5
h      Laura    NaN         1      no         NaN
i      Kevin    8.0         2      no         8.0
j      Jonas   19.0         1     yes        19.0

15. Write a Python program to calculate the sum of the examination attempts by the
students.

In [42]:

def create_and_process_dataframe():
    
    
    """

    Description:
        Creates a pandas DataFrame from predefined exam data, prints the DataFrame, and computes the sum of the 'attempts' column.

    Parameters:
        None

    Returns:
        None
        
    """
   
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    df = pd.DataFrame(data=exam_data, index=labels)

   
    print("DataFrame:")
    print(df)
    print()

    
    attempts_sum = df['attempts'].sum()
    print(f"Sum of 'attempts' column: {attempts_sum}")



def main():

    create_and_process_dataframe()

if __name__ == "__main__":
    main()

DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Sum of 'attempts' column: 19

17. Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame.

In [43]:

def perform_operations(df):
    
    
    """
    Description:
        This function performs various operations on the DataFrame, including adding a new row,
        and deleting the row with the label 'k'.

    Parameters:
        df (pd.DataFrame): The DataFrame to perform operations on.

    Returns:
        pd.DataFrame: The DataFrame after performing operations.
    """

    df.loc['k'] = ['Suresh', 15.5, 1, 'yes']
    print("DataFrame after adding new row:")
    print(df)
    print()
    
    df = df.drop('k')
    print("DataFrame after dropping row 'k':")
    print(df)
    return df

def main():

    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    df = pd.DataFrame(data=exam_data, index=labels)

    df = perform_operations(df)

if __name__ == "__main__":
    main()

DataFrame after adding new row:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

DataFrame after dropping row 'k':
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order.

In [44]:

def sort_dataframe(df):
    
    
    """
    Description:
        This function sorts the DataFrame by 'name' in descending order and 'score' in ascending order.

    Parameters:
        df (pd.DataFrame): The DataFrame to be sorted.

    Returns:
        pd.DataFrame: The sorted DataFrame.
    """
    
    
    sorted_df = df.sort_values(by=['name', 'score'], ascending=[False, True])
    print("Sorted DataFrame:")
    print(sorted_df)
    return sorted_df



def main():

    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    
    df = pd.DataFrame(data=exam_data, index=labels)
    print("Initial DataFrame:")
    print(df)
    print()

    
    df = sort_dataframe(df)

if __name__ == "__main__":
    main()

Initial DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Sorted DataFrame:
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

19. Write a Python program to replace the 'qualify' column contains the values 'yes' and
'no' with True and False.

In [45]:


def process_exam_data(df):
    
    
    """
    Description:
        This function processes the exam DataFrame by converting the 'qualify' column
        to boolean values and then prints the updated DataFrame.
    
    Parameter:
        df (pd.DataFrame): The DataFrame containing exam data.
    
    Return:
        None
    """
    
     
    df['qualify'] = df['qualify'].apply(lambda x: True if x == 'yes' else False)


    print(df)


def main():
 
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    df = pd.DataFrame(data=exam_data, index=labels)
    print(df)
    print()
    process_exam_data(df)


if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

20. Write a Python program to delete the 'attempts' column from the DataFrame.

In [46]:

import pandas as pd
import numpy as np

def process_exam_data(df):
    
    
    """
    Description:
        This function processes the exam DataFrame by dropping the 'attempts' column
        and then printing the updated DataFrame.
    
    Parameter:
        df (pd.DataFrame): The DataFrame containing exam data.
    
    Return:
        None
    """

    df = df.drop('attempts', axis=1)

    print(df)


def main():

    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

    
    df = pd.DataFrame(data=exam_data, index=labels)
    print(df)
    print()
    process_exam_data(df)


if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

21. Write a Python program to insert a new column in existing DataFrame.

In [47]:

def create_and_process_dataframe():
    
    
    """
    
    Description:
        Creates a pandas DataFrame from predefined exam data, calculates the mean score for each student,
        and prints the DataFrame with the mean scores included.

    Parameters:
        None

    Returns:
        None
        
    """
    
    
    
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    df = pd.DataFrame(data=exam_data, index=labels)

    print("Initial DataFrame:")
    print(df)
    print()

    df['mean_score'] = df[['score']].apply(lambda x: x.mean(), axis=1)

 
    
   
    print("DataFrame with Mean Scores:")
    print(df)

def main():
 

    create_and_process_dataframe()

if __name__ == "__main__":
    main()

Initial DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

DataFrame with Mean Scores:
        name  score  attempts qualify  mean_score
a  Anastasia   12.5         1     yes        12.5
b       Dima    9.0         3      no         9.0
c  Katherine   16.5         2     yes        16.5
d      James    NaN         3      no         NaN
e      Emily    9.0         2      no         9.0
f    Michael   20.0         3     yes        20.0
g    Matthew   14.5         1     yes        14.5
h      Laura    NaN         1      no         NaN
i      Kevin    8.0         2      no         8.0
j      Jonas   19.0         1     yes        19.0


23. Write a Python program to insert a new column in existing DataFrame.

In [48]:

def process_exam_data(df):
    
    
    """
    Description:
        This function processes the exam DataFrame by retrieving the column names 
        and printing them as a list.
    
    Parameter:
        df (pd.DataFrame): The DataFrame containing exam data.
    
    Return:
        None
    """
   
    column_list = df.columns.values.tolist()
    

    print(df)
    print()
    print(column_list)


def main():


    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


    df = pd.DataFrame(data=exam_data, index=labels)

    process_exam_data(df)


if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

['name', 'score', 'attempts', 'qualify']

22. Write a Python program to iterate over rows in a DataFrame.

In [49]:

def process_exam_data(df):
    
    
    """
    Description:
        This function processes the exam DataFrame by converting each row into a list
        and appending it to a list of rows.
    
    Parameter:
        df (pd.DataFrame): The DataFrame containing exam data.
    
    Return:
        row_list (list): A list of lists, where each sub-list represents a row from the DataFrame.
    """
    
    
    row_list = []

    for index in range(len(df)):
        row_list.append(df.iloc[index])

    print(df)
    print()
    print(row_list)
    


def main():

   
    exam_data = {
        'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
                 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

  
    df = pd.DataFrame(data=exam_data, index=labels)

  
    process_exam_data(df)


if __name__ == "__main__":
    main()

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

[name        Anastasia
score            12.5
attempts            1
qualify           yes
Name: a, dtype: object, name        Dima
score        9.0
attempts       3
qualify       no
Name: b, dtype: object, name        Katherine
score            16.5
attempts            2
qualify           yes
Name: c, dtype: object, name        James
score         NaN
attempts        3
qualify        no
Name: d, dtype: object, name        Emily
score         9.0
attempts        2
qualify        no
Name: e, dtype: object, name        Michael
score          20.0
attempts          3
qualify         yes
Name: f, dtype: object, name        Matthew
score          14.5
attempts          1
qualify         yes
Name: g, dtype: object, name        Laura
score         NaN
attempts        1
qualify        no
Name: h, dtype: object, name        Kevin
score         8.0
attempts        2
qualify        no
Name: i, dtype: object, name        Jonas
score        19.0
attempts        1
qualify       yes
Name: j, dtype: object]